- name: configure backend server
  become: yes
  hosts: backend
  vars:

  tasks:
  - name: disable default nodejs
    anisble.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:24
    anisble.builtin.command: dnf module enable nodejs -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: installed

  - name: create expense user
    ansible.builtin.user:
      name: expense